name: build
on:
  push:
  pull_request:

permissions:
  checks: write # to create new checks (coverallsapp/github-action)

jobs:
  build:
    permissions:
      contents: read # to fetch code (actions/checkout)
      checks: write # to create new checks (coverallsapp/github-action)

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y
      - run: >
          sudo apt-get install --no-install-recommends -y
          ffmpeg
          gifsicle
          redis
          libcurl4-openssl-dev
          libjpeg-progs
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Fire up Redis
        run: make redis
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}
      - name: Setup
        run: pip install --upgrade --upgrade-strategy eager -e .[tests]
      - name: Compile Extensions
        run: make compile_ext
      - name: Run Unit Tests
        run: make sequential-unit
      - name: Run Integration Tests
        run: make integration_run
      - name: Lint
        run: make pylint
      - name: Generate lcov
        run: coverage lcov
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
          flag-name: run-${{ matrix.image-tag }}
          parallel: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
