name: lint/formatter
on:
  push:
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
  lint:
    permissions:
      contents: read # to fetch code (actions/checkout)
      checks: write # to update checks

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y
      - run: >
          sudo apt-get install --no-install-recommends -y
          ffmpeg
          gifsicle
          redis
          libcurl4-openssl-dev
          libjpeg-progs
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-lint-${{ hashFiles('setup.py') }}
      - name: Setup
        run: pip install --upgrade --upgrade-strategy eager -e .[tests]
      - name: Compile Extensions
        run: make compile_ext
      - name: Lint
        run: make pylint
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - uses: actions/checkout@v2
      - name: Install isort
        run: pip install isort
      - name: Run isort
        run: isort thumbor tests --profile black
